### ISSUE TITLE
cmd+enter like spotlight

### ISSUE THREAD

**Issue by TobiasDoe** [Chao-Man/lacona-find#1]
hey, 
is there a way to make it work as spotlight does it...
just if u press cmd + enter on the app/file/folder to open in in the finder?

this is the only feature why i cant switch 100% to lacona

**Comment by Chao-Man** [comment]
Hey, 
I agree that'd be a great way to handle it.
However, you might want to submit an issue for lacona at:
https://github.com/laconalabs/LaconaApp/issues

This repo is for an addon for lacona.

Cheers.
